export {default as Home } from './home/Home'
export {default as About} from './about/About'
export {default as ShopHome} from  './shop/shopViews/ShopHome'
export {default as Videos } from './videos/Videos'
export {default as Contact } from './contact/Contact'
export {default as SweetShop} from './shop/shopViews/ShopHome'
export {default as Tumblers} from './shop/shopViews/Tumblers'
export {default as Vinyls } from './shop/shopViews/Vinyls'
export {default as Pens } from './shop/shopViews/Pens'
export {default as LoveMugs } from './shop/shopViews/LoveMugs'
export {default as Cart} from './shop/shopComponents/cart/Cart'